# Generated by Django 4.2 on 2023-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ira', '0002_alter_week_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
