# Generated by Django 4.2 on 2023-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ira', '0004_alter_week_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='deposit_kzt',
            new_name='kaspi_deposit_kzt',
        ),
        migrations.AddField(
            model_name='week',
            name='bcc_card',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='bcc_cny',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='bcc_eur',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='bcc_kzt',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='bcc_usd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='kaspi_deposit_usd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
