# Generated by Django 4.2 on 2023-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ira', '0005_rename_deposit_kzt_week_kaspi_deposit_kzt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='week_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер недели'),
        ),
    ]
