# Generated by Django 4.2 on 2023-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ira', '0006_week_week_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('date',), 'verbose_name': 'Неделя', 'verbose_name_plural': 'Недели'},
        ),
        migrations.AlterField(
            model_name='week',
            name='week_number',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Номер недели'),
        ),
    ]
